version: '2'

services:

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=vkhack
      - POSTGRES_PASSWORD=vkhack
    volumes:
      - /var/lib/postgresql/data/

  redis:
    image: redis
    ports:
      - "6379"
    volumes:
      - /data

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./static:/static
    links:
      - groupbot:groupbot

  groupbot:
    env_file: .env
    build:
      context: .
      dockerfile: docker/group_bot/Dockerfile
    depends_on:
      - db
    expose:
      - "8000"
    volumes:
      - .:/workdir/app
    links:
      - db:db
    entrypoint:
      - /workdir/app/docker/group_bot/run.sh
